# Generated by Django 2.1.5 on 2019-01-08 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='usertemp',
            name='device_id',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='access_token_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 13, 29, 12, 405282)),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token_token_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 13, 29, 12, 405282)),
        ),
    ]
