# Generated by Django 2.1.5 on 2019-02-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
