# Generated by Django 2.1.5 on 2019-01-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xgame', '0002_auto_20190108_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=127, null=True, unique=True),
        ),
    ]
