# Generated by Django 2.1.5 on 2019-01-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xgame', '0004_auto_20190115_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
