# Generated by Django 2.1.5 on 2019-01-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xgame', '0005_auto_20190116_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
