# Generated by Django 2.1.5 on 2019-01-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xgame', '0006_auto_20190116_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_id',
            field=models.CharField(default=44, max_length=255),
            preserve_default=False,
        ),
    ]
