# Generated by Django 2.1.5 on 2019-01-08 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xgame', '0008_auto_20190108_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemp',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 11, 29, 49, 375572, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='access_token_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 10, 39, 49, 376570, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 10, 39, 49, 376570, tzinfo=utc)),
        ),
    ]
