# Generated by Django 2.1.5 on 2019-01-18 15:07

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('xgame', '0008_auto_20190116_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=django_mysql.models.ListCharField(models.CharField(max_length=63), max_length=1280, size=20),
        ),
    ]
