# Generated by Django 2.1.5 on 2019-01-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xgame', '0009_auto_20190118_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='hypes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='popularity',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='total_rating',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='total_rating_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
