# Generated by Django 2.1.5 on 2019-01-08 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xgame', '0010_auto_20190108_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='security_code',
        ),
        migrations.AlterField(
            model_name='token',
            name='access_token_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 42, 37, 650859, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 11, 42, 37, 650859, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usertemp',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 11, 42, 37, 649862, tzinfo=utc)),
        ),
    ]
