# Generated by Django 2.1.5 on 2019-01-08 11:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xgame', '0011_auto_20190108_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.TextField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='token',
            name='access_token_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 11, 46, 1, 948539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token',
            field=models.TextField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token_expire',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 11, 46, 1, 948539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usertemp',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 11, 46, 1, 947540, tzinfo=utc)),
        ),
    ]
