# Generated by Django 2.1.5 on 2019-01-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xgame', '0011_auto_20190122_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_expire',
            field=models.DateTimeField(),
        ),
    ]
