# Generated by Django 2.1.5 on 2019-01-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xgame', '0017_auto_20190130_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='hypes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='popularity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='total_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='total_rating_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='seller_photos',
            field=models.ImageField(blank=True, null=True, upload_to='seller_photos/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='trailer',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
